// Clientes absurdos de Puerto Paquete. Todo inventado.
import type { ClientProfile } from './types';

export const CLIENTS: ClientProfile[] = [
  {
    id: 'puri', name: 'Doña Puri', avatar: '👵', look: 'abuela', quirk: 'abuela_centimos', voice: 1.3, districts: ['viejo', 'centro'],
    items: ['un juego de tazas con gatitos', 'tres kilos de pipas', 'una faja reductora', 'un marco de fotos que canta', 'lana para 40 bufandas'],
    ask: [
      'Hola hijo, soy la Puri. Me traes {item}? Te pago {precio}, en suelto que no tengo billetes 👵',
      'Buenas, me ha dicho mi nieto que esto se pide por aquí. {item}. {precio}. Y no corras que te matas.',
      'Cariño, {item} a {calle}. Tienes {tiempo}, que a las ocho empieza el concurso.',
    ],
    happy: ['¡Ay, qué majo! Toma, cuéntalo tú que yo ya no veo.', 'Qué rápido, hijo. Toma una galleta. Bueno, no, que es la última.', 'Toma, hijo. Y llévate un caramelo de la tele, que están un poco pegados.'],
    late: ['Ya ha empezado el concurso. Muy mal. Muy mal todo.', 'Hijo, he envejecido esperando. Más.'],
    broken: ['Esto venía entero cuando lo compré. En la foto.', '¿Pero qué le has hecho a mis tazas? ¡Tenían nombre!', 'Si esto era así de nuevo, que me lo digan, que yo no me acuerdo.'],
  },
  {
    id: 'vecino', name: 'Sergio "no estoy"', avatar: '🙈', look: 'civil', quirk: 'vecino_banda', voice: 0.9,
    items: ['un móvil de segunda mano', 'unas zapatillas de edición limitada', 'una caja misteriosa', 'un dron con una hélice'],
    ask: [
      'Oye mira, {item}, {precio}. Si no estoy déjaselo al vecino, que es de confianza 👍',
      'Traeme {item} a {calle}. Tienes {tiempo}. Si no abro, al vecino del bajo. Es majísimo.',
      '{item} a {calle}, {precio}. Si no contesto, el vecino. Tiene la puerta morada, no tiene pérdida.',
    ],
    happy: ['Gracias, tío. Oye, ¿el vecino te ha dicho algo raro?'],
    late: ['¿Dónde te habías metido? El vecino dice que te esperaba.'],
    broken: ['Viene abollado. El vecino dice que así venía. Qué raro todo.'],
  },
  {
    id: 'kevin', name: 'Kevin (cambia de sitio)', avatar: '🏃', look: 'fiestero', quirk: 'cambia_direccion', voice: 1.0,
    items: ['un altavoz con luces', 'una pizza congelada gigante', 'un flotador de unicornio', 'unas gafas de realidad virtual'],
    ask: [
      'Buenaaas, {item} porfa!! {precio} y te invito a una. Estoy en {calle}. De momento.',
      'Tío necesito {item} YA. {tiempo}. {precio}. Luego te digo dónde estoy exactamente jeje',
    ],
    happy: ['¡Máquina! ¿Te vienes a la fiesta? Es en otra calle.', 'Crack. Te dejo cinco estrellas. Bueno, cuatro.', '¡Eres una leyenda! Te mando la ubicación de la siguiente fiesta. Cambia cada diez minutos.'],
    late: ['Ya se ha acabado la fiesta. Bueno, empieza otra en otro sitio.'],
    broken: ['Da igual, con luces no se nota.'],
  },
  {
    id: 'mari', name: 'Mari y Pancho 🐶', avatar: '🐕', look: 'civil', quirk: 'pijama_perro', voice: 1.1,
    items: ['pienso para perros (el caro)', 'un sofá para perro', 'una pelota que no rebota', 'un abrigo de perro con capucha'],
    ask: [
      'Hola! Soy Mari. Necesito {item} para Pancho. {precio}. Bajo en pijama, no me juzgues.',
      '{item} a {calle}. Pancho no muerde. Casi nunca. {tiempo}.',
    ],
    happy: ['¡Pancho, deja al señor! PANCHO. Perdona, es muy cariñoso.', 'Gracias! Pancho dice que le caes bien. Por eso te persigue.'],
    late: ['Pancho se ha comido el felpudo esperando. Lo pagas tú.', 'Pancho te ha estado esperando en la ventana. Ha llorado. Yo también, un poco.'],
    broken: ['Pancho está decepcionado. Mira su cara.'],
  },
  {
    id: 'anselmo', name: 'Anselmo', avatar: '🤨', look: 'civil', quirk: 'no_he_pedido', voice: 0.75,
    items: ['una batidora industrial', 'un kayak hinchable', 'veinte rollos de papel de cocina', 'un cortacésped', 'un busto de un señor con peluca'],
    ask: [
      'Entrega para Anselmo en {calle}. {item}. {precio}. (Pedido automático)',
      'Paquete: {item}. Cliente: Anselmo. Cobrar: {precio}. Plazo: {tiempo}.',
    ],
    happy: ['...Ah, sí, esto sí lo pedí. Bueno, lo pidió el gato con mi móvil.', 'Esto no lo he pedido. Pero ahora que lo veo, me lo quedo.'],
    late: ['Ya ni me acordaba de que no lo había pedido.'],
    broken: ['Encima de que no lo pedí, roto.'],
  },
  {
    id: 'yenni', name: 'Yenni Influencer ✨', avatar: '🤳', look: 'fiestero', quirk: 'influencer', voice: 1.4, districts: ['centro', 'colina'],
    items: ['un aro de luz gigante', 'un bolso que brilla en la oscuridad', 'una colección de pestañas', 'un trípode con otro trípode'],
    ask: [
      'Holiii repartidooor 💅 {item}, {precio}, y porfa ven guapo que te grabo para mis 3 millones de seguidores ✨',
      '{item} a {calle} en {tiempo}!!! Es para un directo!!! 📸📸',
    ],
    happy: ['¡Saluda a la cámara! Diles "contra reembolso, contra el aburrimiento" ✨', 'Chicos, este es mi repartidor favorito. Dale like.', '¡Qué luz tienes! Bueno, es el aro de luz. Pero tú también.'],
    late: ['Se me ha cortado el directo esperándote. Te voy a funar un poquito.'],
    broken: ['¡Esto es contenido! "Unboxing de cosas rotas". Gracias, supongo.'],
  },
  {
    id: 'regateo', name: 'Paco "el Regateos"', avatar: '🧐', look: 'civil', quirk: 'regatea', voice: 0.85,
    items: ['una bicicleta estática sin sillín', 'un reloj de oro que parece de oro', 'una tele de 90 pulgadas', 'unas cortinas de terciopelo'],
    ask: [
      '{item}. Pone {precio} pero eso lo hablamos en persona, ¿eh? 😏',
      'Buenas. {item} a {calle}. {precio}... bueno, más o menos.',
      '{item} a {calle}. Pone {precio}, pero eso es precio de catálogo. Tú y yo somos más de precio de amigo.',
    ],
    happy: ['Venga, lo que tú digas. Eres duro de pelar.', 'Me has ganado. Toma, y no se lo digas a nadie.'],
    late: ['Por llegar tarde, te pago la mitad. Es la ley del mercado.'],
    broken: ['Roto vale menos. Eso lo sabe todo el mundo.'],
  },
  {
    id: 'villamimosa', name: 'Los señores de Villa Mimosa', avatar: '🥂', look: 'rico', quirk: 'none', voice: 0.9, districts: ['colina'],
    items: ['una lámpara de araña', 'caviar de lata grande', 'un jarrón de la dinastía Ming (de Pekín, no de la dinastía)', 'un flamenco de bronce', 'un piano de juguete para el perro'],
    ask: [
      'Buenas tardes. Rogamos entrega de {item} en {calle}. Abonaremos {precio}. Discreción, por favor.',
      'El servicio está de vacaciones. {item}. {precio}. Tiene {tiempo}. Gracias.',
    ],
    happy: ['Impecable. Tome algo para usted. No, eso no, eso es un cenicero.', 'Qué eficacia. Le recomendaremos en el club de golf.', 'Espléndido. El mayordomo le acompañará a la salida. Ah, no, que está de vacaciones. Salga usted solo.'],
    late: ['La puntualidad es la cortesía de los reyes. Usted es un plebeyo.'],
    broken: ['Hemos recibido el jarrón en formato puzzle. Qué original.'],
  },
  {
    id: 'bar', name: 'Bar Casa Manolo', avatar: '🍺', look: 'civil', quirk: 'none', voice: 0.8, districts: ['viejo', 'puerto'],
    items: ['dos barriles de gaseosa', 'cien servilletas de papel', 'una máquina de hielo', 'la tapa de la freidora'],
    ask: [
      'Manolo al aparato. {item} para el bar YA, que se me acumulan los parroquianos. {precio}.',
      '¡Urgencia hostelera! {item}. {tiempo}. {precio}. Hay caña gratis si llegas.',
    ],
    happy: ['¡Olé! Caña y tapa de la casa. Bueno, la tapa no, que se ha acabado.', '¡Eres el mejor! Ya tienes tu foto en la pared, al lado del de la quiniela.'],
    late: ['Los parroquianos se han ido al bar de enfrente. Traidores.'],
    broken: ['Esto no enfría ni el ambiente.'],
  },
  {
    id: 'gimnasio', name: 'Músculo Feliz (gimnasio)', avatar: '💪', look: 'civil', quirk: 'none', voice: 0.7, prefers: 'pesado',
    items: ['cien kilos de pesas', 'batidos de proteína sabor chorizo', 'un espejo de cuerpo entero', 'una esterilla de yoga reforzada'],
    ask: ['¡VAMOS! {item}! {precio}! {tiempo}! ¡Sin excusas!', 'Entrega PESADA para el gimnasio. {item}. Si te cuesta, es entreno.'],
    happy: ['¡Eso es actitud! ¿Has entrenado pierna hoy? Se nota.'],
    late: ['Nos hemos enfriado. Y eso en un gimnasio es un drama.', 'Hemos hecho cien sentadillas esperándote. Te odiamos con músculos.'],
    broken: ['Da igual, las pesas no se rompen. Bueno, estas sí.'],
  },
  {
    id: 'fiorella', name: 'Fiorella (pastelería)', avatar: '🎂', look: 'civil', quirk: 'none', voice: 1.25, districts: ['centro', 'viejo'], prefers: 'fragil',
    items: ['una tarta de boda de cinco pisos', 'doscientos cruasanes', 'una escultura de azúcar', 'un roscón con sorpresa dentro de la sorpresa'],
    ask: ['¡FRÁGIL! {item}. {precio}. Si se rompe, lloro. Si llega tarde, lloro más.', '{item} a {calle}. Llévala como si fuera un bebé. Un bebé de nata.'],
    happy: ['¡Perfecta! Eres un artista del volante. Toma un cruasán.', '¡Llegó sin una miga fuera de sitio! Voy a llorar de alegría encima del merengue.'],
    late: ['La boda ya ha terminado. Se han casado sin tarta. Qué tristeza.'],
    broken: ['Me han entregado una tarta de un piso y muchos pedacitos.'],
  },
  {
    id: 'misterio', name: 'Número oculto', avatar: '🕶️', look: 'civil', quirk: 'none', voice: 0.65, prefers: 'sospechoso',
    items: ['un maletín que hace tic-tac', 'una caja que no se debe abrir', 'un sobre muy gordo', 'una estatuilla de un pato'],
    ask: ['No hagas preguntas. {item}. {precio}. {tiempo}. Nadie te sigue. Creo.', 'Paquete delicado. {item}. Pago triple: {precio}. Evita a los morados.', '{item}. {tiempo}. {precio}. Si alguien pregunta, eres un repartidor normal. Que lo eres.'],
    happy: ['Esta conversación nunca ha existido. El dinero sí.'],
    late: ['Llegas tarde. Eso tiene consecuencias. O no. Ya veremos.'],
    broken: ['Espero que no hayas mirado dentro.'],
  },
  {
    id: 'profe', name: 'Profesor Bartolo', avatar: '🧑‍🏫', look: 'civil', quirk: 'none', voice: 0.95,
    items: ['treinta exámenes corregidos', 'un esqueleto de plástico', 'un globo terráqueo con Puerto Paquete', 'una pizarra de dos metros'],
    ask: ['Estimado repartidor: {item}. Remuneración: {precio}. Plazo: {tiempo}. Sea puntual, que le pongo falta.'],
    happy: ['Un diez. Bueno, un nueve con cinco, que ha pitado al llegar.'],
    late: ['Suspenso. Recuperación en septiembre.', 'Llega tarde. Escriba cien veces «no llegaré tarde». En la furgoneta, si quiere.'],
    broken: ['Esto, técnicamente, ya no es un esqueleto. Es un puzzle.'],
  },
  {
    id: 'pescador', name: 'Tío Ramón (pescador)', avatar: '🎣', look: 'civil', quirk: 'none', voice: 0.8, districts: ['puerto'],
    items: ['cebo vivo (muy vivo)', 'una red nueva', 'un ancla pequeñita', 'hielo para el pescado'],
    ask: ['Chaval, {item} al muelle. {precio}. Corre que se me escapa la marea.', '{item} en {calle}. Huele un poco. Mucho. {precio}.'],
    happy: ['¡Así se hace, marinero! Toma una sardina. Es de ayer.', '¡Ese es mi chaval! Esta noche, calderete. Tú traes el pan.'],
    late: ['Se me ha ido la marea y el cebo. El cebo andando.'],
    broken: ['El hielo roto sigue siendo hielo. Te salvas.'],
  },
  {
    id: 'hacker', name: 'Lucía_404', avatar: '💻', look: 'civil', quirk: 'none', voice: 1.15,
    items: ['un teclado mecánico que suena a máquina de escribir', 'cuarenta latas de bebida energética', 'una silla gamer con reposapiés', 'un ventilador para el ordenador'],
    ask: ['hola. {item}. {precio}. {tiempo} o me muero de sed. literal.', 'pedido urgente para {calle}. {item}. no llames al timbre que me asusto.'],
    happy: ['gg. te doy 5 estrellas y un gif de un gato.', 'entregado. he subido tu reputación en internet. no preguntes cómo.'],
    late: ['lag. mucho lag.'],
    broken: ['error 404: paquete entero no encontrado.'],
  },
  {
    id: 'concejal', name: 'El Concejal Pérez', avatar: '🎩', look: 'rico', quirk: 'regatea', voice: 0.85,
    items: ['una banda de "Hijo predilecto"', 'cien banderitas', 'unas tijeras gigantes para inaugurar cosas', 'una placa conmemorativa con errata'],
    ask: ['Desde el Ayuntamiento: {item}. {precio} (presupuesto aprobado, más o menos). {tiempo}.'],
    happy: ['El Ayuntamiento le agradece los servicios prestados. Y le debe una rotonda.'],
    late: ['Tendremos que inaugurar la fuente sin tijeras. Con los dientes.', 'Llega usted tarde. Como las obras de la rotonda. Le perdono por solidaridad.'],
    broken: ['Lo declaramos patrimonio roto de la humanidad.'],
  },
  // ───────────── Fase 8: más clientes absurdos ─────────────
  {
    id: 'opositor', name: 'Chema (opositor, 11.º año)', avatar: '📚', look: 'civil', quirk: 'none', voice: 0.9,
    items: ['el tomo 47 del temario', 'tres kilos de subrayadores', 'un flexo que ilumina el alma', 'café en polvo para untar'],
    ask: [
      'Buenas. Oposito desde hace once años y no puedo salir de casa. {item}. {precio}. {tiempo}. No toques el timbre, que pierdo el hilo.',
      'Me faltan 4.000 temas y {item}. Te pago {precio}. Estoy en {calle}, entre apuntes.',
      'Tema 38: «{item}». Lo necesito en {calle} en {tiempo}. {precio}. Entra en el examen, seguro.',
    ],
    happy: ['Gracias. Este año apruebo. Como los otros once.', 'Me has ahorrado siete minutos de estudio. Los usaré para agobiarme.'],
    late: ['He perdido el ritmo. Vuelvo a empezar por el tema uno. Otra vez.'],
    broken: ['El temario viene en fascículos sueltos. Bueno, así se estudia por partes.'],
  },
  {
    id: 'encarna', name: 'Doña Encarna (la del quinto)', avatar: '👀', look: 'abuela', quirk: 'none', voice: 1.25, districts: ['viejo', 'centro', 'puerto'],
    items: ['unos prismáticos de largo alcance', 'un vaso para escuchar paredes', 'una silla plegable para el balcón', 'una libreta gorda para apuntar matrículas'],
    ask: [
      'Hijo, {item}, que en el tercero pasa algo y necesito verlo bien. {precio}. {tiempo}.',
      'Tráeme {item} a {calle}. Y de paso me cuentas quién vive en la casa amarilla. {precio}.',
    ],
    happy: ['Ay, gracias. Oye, ¿tú no eres el que salía con la de la frutería?', 'Qué majo. Por cierto, tu furgoneta pierde aceite. Lo tengo apuntado.', 'Qué rápido. Por cierto, la del cuarto se ha cortado el pelo. Fatal, además.'],
    late: ['Ya se han ido todos del tercero y me lo he perdido. Se lo pienso contar a todo el barrio.'],
    broken: ['Con esto roto no veo ni el portal. Menos mal que tengo el oído fino.'],
  },
  {
    id: 'rigoberto', name: 'Rigoberto (ventanilla 3)', avatar: '📋', look: 'civil', quirk: 'firmas', voice: 0.8,
    items: ['un sello con tres sellos dentro', 'quinientos impresos por triplicado', 'una grapadora industrial', 'un archivador de archivadores'],
    ask: [
      'Envío de {item} a {calle}. Importe: {precio}. Plazo: {tiempo}. Traiga el DNI, una fotocopia del DNI y una fotocopia de la fotocopia.',
      'Buenos días. {item}. {precio}. Si no estoy, vuelva mañana. Si estoy, también.',
    ],
    happy: ['Todo en regla. Su expediente queda archivado en el cajón de los expedientes.', 'Correcto. Le devolveremos la llamada en un plazo de tres a cuarenta años.'],
    late: ['Fuera de plazo. Tendrá que pedir cita para pedir cita.', 'Llega usted fuera de horario. El horario es de nueve a nueve y cuarto.'],
    broken: ['Viene dañado. Rellene el formulario de daños. Está dentro del paquete. Que viene dañado.'],
  },
  {
    id: 'pena', name: 'Peña Los Chunda-Chunda', avatar: '🥁', look: 'fiestero', quirk: 'cambia_direccion', voice: 1.1,
    items: ['un bombo más grande que tú', 'cuarenta pañuelos de fiestas', 'una charanga desmontable', 'confeti para tres pueblos'],
    ask: [
      '¡EEEH REPARTIDOOOR! ¡{item}! {precio} y te hacemos socio de la peña. Estamos en {calle}. Creo.',
      'La peña necesita {item} en {tiempo}. {precio}. Si nos movemos, síguenos por el ruido.',
    ],
    happy: ['¡Socio de honor! El carnet te llega en fiestas. Del año que viene.', '¡OEEE, OEEE! ¡Ese repartidor!', '¡Ese repartidor, ese repartidor! (lo cantan con bombo)'],
    late: ['Ya han pasado la procesión, el desfile y la resaca. Pero gracias.'],
    broken: ['El bombo suena raro. Da igual, nosotros también.'],
  },
  {
    id: 'mago', name: 'Maese Ulises (mago de cumpleaños)', avatar: '🪄', look: 'civil', quirk: 'no_he_pedido', voice: 1.0,
    items: ['un conejo de peluche (el de verdad se escapó)', 'una baraja con sesenta ases', 'una caja para serrar gente', 'palomas de goma'],
    ask: [
      '¡Tachán! Necesito {item} para un cumpleaños. {precio}. {tiempo}. Si no me ves, es parte del truco.',
      '{item} a {calle}. Pago {precio}. O lo hago aparecer, todavía no lo sé.',
    ],
    happy: ['¿Es este su paquete? ¡Tachán! Sí, era este.', 'Gracias. Elige una carta. No, esa no. Da igual, ya te puedes ir.'],
    late: ['Los niños se han ido. Los he hecho desaparecer. Bueno, se han ido solos.', 'He hecho desaparecer la paciencia de los niños. Sin varita.'],
    broken: ['Ahora el número se llama «la caja serrada de verdad». También vale.'],
  },
  {
    id: 'bodas', name: 'Paquita (organiza bodas)', avatar: '💍', look: 'rico', quirk: 'none', voice: 1.2, districts: ['colina', 'centro'], prefers: 'fragil',
    items: ['una tarta de nueve pisos', 'dos palomas mensajeras con resaca', 'trescientas copas de cristal fino', 'el vestido de la novia (con cola de veinte metros)'],
    ask: [
      '¡Emergencia nupcial! {item} a {calle}. {precio}. {tiempo}. La novia está llorando, pero de las buenas.',
      'FRÁGIL, FRÁGIL, FRÁGIL. {item}. {precio}. Si se rompe, se suspende la boda y te caso a ti.',
    ],
    happy: ['¡Divino! Quédate al banquete: mesa 47, al lado de los cuñados.', 'La novia dice que eres el segundo hombre más guapo del día.', 'Te has ganado un trozo de tarta. Del piso de abajo, el de los invitados normales.'],
    late: ['Se han casado ya. Han brindado con agua del grifo. Ha sido muy triste.'],
    broken: ['Ahora la tarta es de un solo piso. El de abajo.'],
  },
  {
    id: 'tuning', name: 'Jonathan «el Tuning»', avatar: '🔊', look: 'fiestero', quirk: 'regatea', voice: 0.95, districts: ['poligono', 'viejo', 'puerto'],
    items: ['un alerón para una bici', 'luces de neón para los bajos', 'un tubo de escape que suena a dragón', 'un volante de peluche de leopardo'],
    ask: [
      'Illo, {item}. Te doy {precio}, pero eso lo hablamos, ¿eh? Estoy en {calle}.',
      'Bro, {item} pa ya. {tiempo}. {precio}. Si llegas rápido te dejo oír el coche.',
    ],
    happy: ['¡Tope guapo! Escucha, escucha: BRRRRRM. ¿Qué? ¿QUÉ?', 'Te has ganado una pegatina en la luna. Mírala, brilla.', 'Illo, qué crack. Te pongo en los agradecimientos del próximo alerón.'],
    late: ['Tarde, bro. Ya he tuneado el coche con cinta aislante.'],
    broken: ['Viene reventao. Mejor, así tiene un rollo más callejero.'],
  },
  {
    id: 'monjas', name: 'Sor Remedios', avatar: '⛪', look: 'abuela', quirk: 'none', voice: 1.2,
    items: ['doscientas yemas de convento', 'un órgano de iglesia portátil', 'velas con olor a «incienso intenso»', 'una bicicleta para llegar antes a misa'],
    ask: [
      'Paz y bien, hijo. {item}, si Dios quiere y tú también. {precio}. {tiempo}.',
      'Las hermanas necesitamos {item} en {calle}. Pagamos {precio} y una oración de las buenas.',
    ],
    happy: ['Que el Señor te lo pague. Bueno, ya te pagamos nosotras. Toma.', 'Bendito seas. Y bendita tu furgoneta, que buena falta le hace.'],
    late: ['Hemos rezado para que llegaras. Ha tardado en funcionar.', 'Llegas con el Ángelus pasado, hijo. Y casi con el de mañana.'],
    broken: ['Las yemas han llegado en forma de revuelto. Dios aprieta pero no ahoga.'],
  },
  {
    id: 'chef', name: 'Chef Ramiro (cocina de autor)', avatar: '👨‍🍳', look: 'rico', quirk: 'none', voice: 0.9, districts: ['centro', 'puerto', 'colina'], prefers: 'urgente',
    items: ['espuma de croqueta deconstruida', 'un kilo de brisa marina embotellada', 'una tortilla SIN cebolla (bajo protesta)', 'caviar de gazpacho'],
    ask: [
      'URGENTE. {item}. Tengo a un crítico en la mesa cinco. {precio}. {tiempo}. ¡VOLANDO!',
      '{item} a {calle}. {precio}. Si tardas, el crítico se come la servilleta.',
    ],
    happy: ['¡Magnífico! El crítico ha llorado. De emoción, creo.', 'Te invito a un menú degustación: tres guisantes y una lágrima.', 'Perfecto. Esto merece una ovación. En la carta: «repartidor al punto».'],
    late: ['El crítico nos ha puesto una estrella. De cinco. Y era por la silla.'],
    broken: ['«Paquete destrozado sobre lecho de disgusto». Lo pongo en la carta.'],
  },
  {
    id: 'toni', name: 'Toñi (la del bingo)', avatar: '🎟️', look: 'abuela', quirk: 'abuela_centimos', voice: 1.35, districts: ['viejo', 'centro'],
    items: ['un rotulador fosforito de la suerte', 'un cojín para aguantar cuatro horas de bingo', 'setenta cartones plastificados', 'una estampita del santo de la suerte'],
    ask: [
      '¡Línea! Digo… hola, guapo. {item}, que esta noche canto bingo. {precio}, en calderilla del premio.',
      'Tráeme {item} a {calle}. {tiempo}, que empieza la partida. Pago {precio}. En suelto, eso sí.',
    ],
    happy: ['¡BINGO! Ah, no, que es el paquete. Toma, cariño.', 'Qué suerte me das. Esta noche me forro. Bueno, esta noche pierdo 20 €, como siempre.'],
    late: ['Ya han cantado bingo. La de la mesa de al lado. Qué rabia me da esa mujer.', 'Llegas tarde y encima me has quitado la suerte. Pero pasa, pasa.'],
    broken: ['Roto, como mi racha. Toma, anda.'],
  },
  {
    id: 'destrozos', name: 'Dani Destrozos (canal de retos)', avatar: '🎥', look: 'fiestero', quirk: 'influencer', voice: 1.2,
    items: ['una sandía gigante para aplastarla', 'cien huevos para un reto', 'una prensa hidráulica de juguete', 'un coche teledirigido blindado'],
    ask: [
      '¡¡QUÉ PASA, FAMILIA!! Necesito {item} para el vídeo de hoy. {precio}. {tiempo}. ¡Dale a la campanita!',
      '¡{item} a {calle}! Si llega roto, mejor, que me ahorras trabajo. {precio}.',
    ],
    happy: ['¡Saluda al chat! Dicen que tienes cara de repartidor honrado.', '¡Brutal! Suscríbete, bro. No, en serio, suscríbete.'],
    late: ['El directo se ha quedado en dos espectadores: mi madre y tú.'],
    broken: ['¡ROTO! ¡Me has hecho el vídeo! «Repartidor destroza mi paquete (REAL, NO FAKE)».'],
  },
  {
    id: 'capitan', name: 'Capitán Merluza', avatar: '⚓', look: 'civil', quirk: 'none', voice: 0.7, districts: ['puerto'],
    items: ['un loro que solo dice «reembolso»', 'un parche de ojo con estampado de flores', 'un mapa del tesoro de la despensa', 'un timón de repuesto (el otro lo perdí)'],
    ask: [
      '¡Arrr, grumete! {item} al muelle. Pago {precio} en doblones. Bueno, en euros. {tiempo}.',
      '{item} a {calle}. {precio}. Si no llegas a tiempo, te hago caminar por la tabla.',
      '¡Grumete! {item} a {calle} antes de {tiempo}, que sube la marea. {precio} en monedas del tesoro.',
    ],
    happy: ['¡Arrr! Buen trabajo, grumete. Te nombro contramaestre. No se cobra más.', '¡Por todas las merluzas! Toma tus doblones.'],
    late: ['El barco zarpó sin mí. Estoy en tierra. Llorando. Arrr.'],
    broken: ['Llega como mi barco: medio hundido. Arrr.'],
  },
  {
    id: 'gatos', name: 'Gertrudis y sus 14 gatos', avatar: '🐈', look: 'abuela', quirk: 'none', voice: 1.3, districts: ['viejo', 'colina', 'centro'],
    items: ['un rascador de tres plantas', 'catorce latas de paté para gatos', 'un sofá para gatos (el mío ya es suyo)', 'una fuente de agua con cascada'],
    ask: [
      'Hola, soy Gertrudis. Los gatos necesitan {item}. Pago {precio}. {tiempo}, que se ponen nerviosos.',
      '{item} a {calle}. {precio}. Si ves un gato naranja en la puerta, es Mandarino. Mételo en casa, porfa.',
    ],
    happy: ['Los catorce te dan las gracias. Bueno, trece. Bigotes nunca da las gracias.', 'Toma. Y llévate un gato si quieres. No, en serio, llévate uno.', 'Mandarino te ha dado su aprobación. Eso es más difícil que sacarse una carrera.'],
    late: ['Los gatos han tirado todo lo que había en las estanterías. De aburrimiento.'],
    broken: ['Da igual que esté roto: van a jugar con la caja. Siempre juegan con la caja.'],
  },
  {
    id: 'nacho', name: 'Nacho «Mañana empiezo»', avatar: '🥱', look: 'civil', quirk: 'none', voice: 0.95, prefers: 'pesado',
    items: ['una cinta de correr que acabará de perchero', 'unas pesas que acabarán de sujetapuertas', 'una bici estática para colgar la ropa', 'una colchoneta para hacer abdominales (mañana)'],
    ask: [
      'Holaaa. {item}. Es PESADO, lo siento. Es que mañana empiezo a entrenar. {precio}.',
      '{item} a {calle}. {precio}. {tiempo}. Súbemelo, porfa, que yo aún no estoy en forma.',
    ],
    happy: ['Genial. Lo dejo aquí y empiezo mañana. O el lunes. El lunes seguro.', 'Gracias, crack. Me canso solo de verte cargarlo.'],
    late: ['Bueno, como ya es tarde, empiezo la semana que viene.', 'Tranquilo, llegar tarde también es un deporte. El mío, en concreto.'],
    broken: ['Viene roto. Pues nada, ya tengo excusa para no empezar.'],
  },
  {
    id: 'turista', name: 'Ingrid (turista despistada)', avatar: '🗺️', look: 'civil', quirk: 'none', voice: 1.3, districts: ['centro', 'puerto', 'colina'],
    items: ['un mapa de Puerto Paquete puesto al revés', 'crema solar de factor 900', 'un diccionario de gestos españoles', 'una paella congelada para seis'],
    ask: [
      '¡Hola! Yo querer {item}. Pagar {precio}. Estoy en {calle}… o eso dice el mapa. {tiempo}.',
      '¡Holaaa! {item}, por favor. {precio}. Hoy me he perdido tres veces. Esta es la cuarta.',
    ],
    happy: ['¡Muchas gracias! ¡Olé! ¿Se dice así? ¿Olé?', '¡Qué amable! En mi país esto tarda tres semanas y llega en otra caja.', '¡Gracias! ¡Es mi primer paquete contra reembolso! Me lo llevo de recuerdo. Con la caja.'],
    late: ['Ya he cenado. A las siete. Aquí la gente me mira raro.'],
    broken: ['¿Aquí las cosas siempre llegan así? Lo pondré en mi guía.'],
  },
  {
    id: 'loli', name: 'Loli (siempre en el bar)', avatar: '🍻', look: 'civil', quirk: 'vecino_banda', voice: 1.15, districts: ['viejo', 'puerto', 'poligono'],
    items: ['un mando universal para la tele', 'unas cortinas opacas', 'un colchón hinchable de matrimonio', 'una freidora de aire'],
    ask: [
      'Estoy en el bar, cariño. {item}, {precio}. Déjaselo al vecino del segundo, que es de fiar. Creo.',
      '{item} a {calle}. No estaré. Te lo recoge el vecino, que es muy majo. Siempre va de morado.',
      'Cariño, {item} a {calle}. {precio}. Yo estoy en el bar, pero el vecino sale enseguida. Siempre sale enseguida.',
    ],
    happy: ['Ay, gracias. ¿El vecino te ha tratado bien? Últimamente está muy raro.'],
    late: ['He vuelto del bar y ni rastro. Me vuelvo al bar.'],
    broken: ['El vecino dice que así venía. El vecino dice muchas cosas.'],
  },
  // ───────────── Fase 9: clientes con manías nuevas ─────────────
  {
    id: 'enigmo', name: 'Don Enigmo (el de los acertijos)', avatar: '🧩', look: 'rico', quirk: 'acertijo', voice: 0.8,
    items: ['un cubo de colores sin resolver desde 1987', 'un crucigrama del tamaño de una sábana', 'un laberinto para hámsteres', 'una esfinge de escayola'],
    ask: [
      'Adivina, adivinanza: ¿qué llega en caja y se paga al recibir? Exacto: {item}. {precio}. {tiempo}.',
      'Te propongo un enigma: {item} en {calle} en menos de {tiempo}. Recompensa: {precio}. Y un acertijo de regalo.',
    ],
    happy: ['Correcto. Como siempre. Bueno, como casi siempre.', 'Un repartidor que piensa. Esto no lo había visto nunca.'],
    late: ['¿Qué llega tarde y aun así quiere cobrar? Tú. No tiene gracia.'],
    broken: ['¿Qué está roto por fuera y roto por dentro? Mi paquete. Esa era fácil.'],
  },
  {
    id: 'gemelos', name: 'Los gemelos Tomás y Tomás', avatar: '👯', look: 'civil', quirk: 'gemelos', voice: 1.0,
    items: ['dos bicicletas exactamente iguales', 'un jersey de dos cuellos', 'dos cepillos de dientes (uno de cada uno)', 'una tarta con dos velas idénticas'],
    ask: [
      'Hola, soy Tomás. El otro Tomás no, este. {item}, {precio}, {tiempo}.',
      '{item} a {calle}. Paga el Tomás que lo ha pedido. Adivina cuál. {precio}.',
    ],
    happy: ['¡Gracias! —¡Gracias! (sí, lo hemos dicho a la vez)', 'Adiós. —Adiós. —¡Deja de copiarme! —¡Deja de copiarme!'],
    late: ['Tarde. —Tarde. —Deja de repetir lo que digo. —Deja de repetir lo que digo.'],
    broken: ['Viene roto. —Viene roto. —¡Que te calles!'],
  },
  {
    id: 'fermin', name: 'Fermín (muy tímido)', avatar: '🫣', look: 'civil', quirk: 'timido', voice: 0.9,
    items: ['unos auriculares con cancelación de gente', 'una cortina para tapar la otra cortina', 'un felpudo que pone «vete»', 'un libro: «Cómo hablar con repartidores»'],
    ask: [
      'h-hola… ¿me traes {item}? {precio}… si no es molestia… {tiempo}…',
      'Perdona que escriba… {item} a {calle}… {precio}… no hace falta que llames… ni que me mires…',
    ],
    happy: ['G-gracias… ya te puedes ir… digo… gracias…', '(se ha puesto rojo como un tomate) …gracias.'],
    late: ['No pasa nada… de verdad… (sí que pasa)'],
    broken: ['Está roto… pero no te lo iba a decir… ya te lo he dicho… perdón…'],
  },
  {
    id: 'fuensanta', name: 'Tía Fuensanta (la huerta)', avatar: '🍉', look: 'abuela', quirk: 'en_especie', voice: 1.2, districts: ['viejo', 'poligono', 'puerto'],
    items: ['semillas de sandía gigante', 'un espantapájaros con gafas de sol', 'una manguera de treinta metros', 'abono de primera (no lo huelas)'],
    ask: [
      'Buenas, sobrino. {item} para la huerta. Te pago {precio}. O en melones, que tengo muchos.',
      '{item} a {calle}, que es para ya: {tiempo}. {precio}. Si prefieres fruta, se habla.',
    ],
    happy: ['¡Qué majo! Llévate un melón. Llévate dos.', 'Así da gusto. Mis melones curan todo: el hambre, la pena y los golpes.'],
    late: ['Se me ha secado una lechuga esperando. Una lechuga entera, ¿eh?'],
    broken: ['Roto da igual: la tierra se lo come todo.'],
  },
  {
    id: 'sospechas', name: 'Don Sospechas', avatar: '🔍', look: 'civil', quirk: 'desconfiado', voice: 0.8,
    items: ['una lupa que ve a través de las cajas', 'un detector de mentiras de juguete', 'una gabardina con veinte bolsillos', 'un bigote postizo (para un amigo)'],
    ask: [
      '{item}. {precio}. {tiempo}. Y no lo agites, que me entero.',
      'Te estaré vigilando. {item} a {calle}. {precio}. Nada de agitar.',
    ],
    happy: ['Hmm. Todo en orden. Demasiado en orden…', 'Te has ganado mi confianza. Durante cinco minutos.'],
    late: ['Tarde. Muy sospechoso. Lo apunto.'],
    broken: ['Lo sabía. LO SABÍA.'],
  },
  {
    id: 'yoli', name: 'Yoli Zumba (profe de baile)', avatar: '💃', look: 'fiestero', quirk: 'baile', voice: 1.25, districts: ['centro', 'viejo', 'colina'],
    items: ['unas mallas de lentejuelas', 'un altavoz para dar clase en la plaza', 'cien metros de serpentina', 'un espejo de pared para la academia'],
    ask: [
      '¡Holaaa! ¡{item} para la academia! {precio}. ¡Y ven con ganas de bailar! 💃',
      '{item} a {calle} en {tiempo}. {precio}. Ya sabes: en mi casa se cobra bailando.',
    ],
    happy: ['¡Eso es ritmo! ¡Te apunto a la clase de los jueves!', '¡Qué caderas! Bueno… qué caderas, más o menos.'],
    late: ['Ya se ha acabado la clase. Hemos bailado sin música, que es lo mismo pero más triste.'],
    broken: ['Roto, como mi rodilla desde el 98. ¡Pero con arte!'],
  },
  {
    id: 'rufino', name: 'Rufino «el Apostador»', avatar: '🪙', look: 'fiestero', quirk: 'moneda', voice: 0.9,
    items: ['una baraja marcada (dice que no)', 'unos dados de la suerte', 'una visera verde de crupier', 'un trébol de cuatro hojas de plástico'],
    ask: [
      '¿Qué te apuestas a que no me traes {item} en {tiempo}? {precio}. Bueno, ya lo hablamos en la puerta.',
      '{item} a {calle}. {precio}. O el doble. O la mitad. Lo echamos a suertes.',
    ],
    happy: ['¡La suerte está echada! Y la tuya, cobrada.', 'Hoy es mi día de suerte. Bueno, el tuyo.'],
    late: ['Aposté a que llegabas tarde. He ganado. Qué rabia me da.'],
    broken: ['Me aposté a que llegaría roto. Odio ganar así.'],
  },
  {
    id: 'chiqui', name: 'Chiqui (cómico de bar)', avatar: '🎤', look: 'fiestero', quirk: 'chistes', voice: 1.1, districts: ['viejo', 'centro', 'puerto'],
    items: ['una nariz de payaso de repuesto', 'un micrófono que funciona a ratos', 'un cojín que hace ruidos', 'un libro de chistes malos (tomo II)'],
    ask: [
      '¿Sabes qué es un repartidor con prisa? Tú, trayéndome {item}. {precio}. {tiempo}. ¡Ba-dum-tss!',
      '{item} a {calle}. {precio}. Si llegas, te cuento un chiste. Si no, también.',
    ],
    happy: ['¡Gracias, eres un público estupendo!', 'Toma. Y de propina otro chiste: ¿qué le dice un paquete a otro? Nada, los paquetes no hablan.'],
    late: ['Llegas tarde. Como mis chistes. Siempre.'],
    broken: ['¡Roto! Esto va directo al número de esta noche.'],
  },
];

/** Tiendas donde se recogen paquetes, con nombre gracioso. */
export const PICKUP_NAMES: Record<string, string> = {
  office: 'la Oficina de Reparto',
};
